### ISSUE TITLE
hash_to_curve uses rejection sampling for EdwardsPoint

### ISSUE THREAD

**Issue by louisabraham** [novifinancial/opaque-ke#37] opened 2020-08-23 07:26 UTC
Hi, I'm new to this project so I'm not sure whether you use this function but it looks like the current implementation of hash_to_curve for EdwardsPoint uses rejection sampling, which is sensitive to timing attacks and strongly advocated against in https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/

**Comment by kevinlewi** [comment] 2020-08-31 20:57
Agreed -- ccing @huitseeker, the problem is that we currently do not have an Elligator-2 implementation in Rust. Hopefully we can fix this soon!

**Comment by huitseeker** [comment] 2020-09-14 12:08
Fixed in #46

**Closed by huitseeker** 2020-09-14 12:08 UTC
