### ISSUE TITLE
Wasm32-unknown-unknown 

### ISSUE THREAD

**Issue by charleschege** [novifinancial/opaque-ke#173] opened 2021-06-15 07:22 UTC
Document on how to compile for the browser, when I try compiling for the browser which is wasm32-unknown-unknown, I get the error `the wasm32-unknown-unknown target is not supported by default, you may need to enable the js feature..... `

**Comment by charleschege** [comment] 2021-06-15 07:23
I need to compile this for the browser, how do I do that

**Comment by kevinlewi** [comment] 2021-06-15 08:05
Hi @charleschege, can you try using https://github.com/marucjmar/opaque-wasm and perhaps filing an issue there? Unless the issue is specific to the opaque Rust implementation.

Closing for now but feel free to reopen if you think it is more relevant to this repo. Thanks!

**Closed by kevinlewi** 2021-06-15 08:05 UTC
